"""
Real-time request-response test for the miner.

Simulates exactly what the validator does when it sends a challenge.
Run with the miner already running on port 8001.

Usage:
    # Terminal 1 - start miner:
    uvicorn miner.main:app --host 0.0.0.0 --port 8001

    # Terminal 2 - run this test:
    python test_miner_curl.py
"""

import asyncio
import json
import os
import time

import httpx
from dotenv import load_dotenv

load_dotenv()

MINER_URL   = os.getenv("MINER_URL", "http://localhost:8001")
WALLET_NAME = os.getenv("WALLET_NAME", "test-validator")
HOTKEY_NAME = os.getenv("HOTKEY_NAME", "default")

# ── Test 1: /availability (no auth) ────────────────────────────────────────

def test_availability():
    print("\n" + "="*60)
    print("TEST 1: GET /availability  (no auth needed)")
    print("="*60)
    print(f"  curl {MINER_URL}/availability")
    print()

    r = httpx.get(f"{MINER_URL}/availability")
    print(f"  Status : {r.status_code}")
    print(f"  Body   : {r.text}")

    if r.status_code == 200 and r.json().get("available") is not None:
        print("  ✓ PASSED — miner is reachable")
    else:
        print("  ✗ FAILED — miner not responding correctly")

    return r.status_code == 200


# ── Test 2: /irrigation/challenge (signed request) ─────────────────────────

async def test_challenge():
    print("\n" + "="*60)
    print("TEST 2: POST /irrigation/challenge  (signed request)")
    print("="*60)

    # Load validator keypair (same one the real validator uses)
    try:
        from fiber.chain import chain_utils
        keypair = chain_utils.load_hotkey_keypair(WALLET_NAME, HOTKEY_NAME)
        print(f"  Validator hotkey : {keypair.ss58_address}")
    except Exception as e:
        print(f"  ✗ Could not load keypair: {e}")
        return False

    # The challenge payload — same format validator sends
    challenge_payload = {
        "challenge_id":     "test-curl-001",
        "latitude":          18.1451,
        "longitude":        100.1407,
        "area_rai":          10.0,
        "query_date":       "2024-06-15",
        "grid_resolution_m": 20,
        "nonce":            f"test-nonce-{int(time.time())}",
        "timestamp_utc":    int(time.time()),   # must be recent (< 90s old)
        "is_canary":         False,
    }

    print(f"\n  Payload being sent:")
    print(f"    challenge_id = {challenge_payload['challenge_id']}")
    print(f"    latitude     = {challenge_payload['latitude']}")
    print(f"    longitude    = {challenge_payload['longitude']}")
    print(f"    query_date   = {challenge_payload['query_date']}")
    print()

    # Get the miner's hotkey from the chain so the header is correct
    # For testing, we use the validator's own hotkey as miner_hotkey
    # (in production the validator looks this up from the metagraph)
    miner_hotkey = os.getenv("MINER_HOTKEY", keypair.ss58_address)

    # Use fiber's signed client — this handles signing automatically
    try:
        from fiber.validator import client as validator_client

        async with httpx.AsyncClient(timeout=120.0) as http_client:
            print("  Sending signed request (fiber handles the crypto signing)…")
            print(f"  curl equivalent:")
            print(f"    curl -X POST {MINER_URL}/irrigation/challenge \\")
            print(f"      -H 'Bt-Header-Validator-Hotkey: {keypair.ss58_address}' \\")
            print(f"      -H 'Bt-Header-Miner-Hotkey: {miner_hotkey}' \\")
            print(f"      -H 'Bt-Header-Nonce: <auto-generated>' \\")
            print(f"      -H 'Bt-Header-Signature: <auto-signed>' \\")
            print(f"      -H 'Content-Type: application/json' \\")
            print(f"      -d '{{\"latitude\": 18.1451, ...}}'")
            print()

            t_start = time.time()
            response = await validator_client.make_non_streamed_post(
                httpx_client=http_client,
                server_address=MINER_URL,
                validator_ss58_address=keypair.ss58_address,
                miner_ss58_address=miner_hotkey,
                keypair=keypair,
                endpoint="/irrigation/challenge",
                payload=challenge_payload,
                timeout=120.0,
            )
            elapsed = time.time() - t_start

    except Exception as e:
        print(f"  ✗ Request failed: {e}")
        return False

    print(f"  Status  : {response.status_code}")
    print(f"  Time    : {elapsed:.2f}s")
    print()

    if response.status_code != 200:
        print(f"  ✗ FAILED — {response.text[:200]}")
        return False

    data = response.json()

    # Show the response fields
    print("  Response fields:")
    print(f"    challenge_id       = {data.get('challenge_id')}")
    print(f"    miner_hotkey       = {data.get('miner_hotkey', '')[:20]}…")
    print(f"    confidence_overall = {data.get('confidence_overall')}")
    print(f"    processing_time_ms = {data.get('processing_time_ms')} ms")
    print(f"    model_version      = {data.get('model_version')}")
    print(f"    satellite_scene_ids= {data.get('satellite_scene_ids')}")
    print(f"    signature          = {data.get('signature', '')[:20]}…")

    grid = data.get("geojson_grid", {})
    features = grid.get("features", [])
    print(f"    geojson grid cells = {len(features)}")

    if features:
        sample = features[0]["properties"]
        print(f"\n  Sample grid cell properties:")
        for k, v in list(sample.items())[:8]:
            print(f"    {k:25s} = {v}")

    print()
    if data.get("confidence_overall", -1) >= 0 and len(features) > 0:
        print("  ✓ PASSED — miner returned a real field analysis response")
    elif data.get("confidence_overall") == 0 and not features:
        print("  ⚠ PARTIAL — miner responded but with empty grid (satellite fetch may have failed)")
    else:
        print("  ✗ FAILED — response missing expected fields")

    # Save full response to file for inspection
    with open("test_miner_response.json", "w") as f:
        json.dump(data, f, indent=2)
    print(f"\n  Full response saved to: test_miner_response.json")

    return response.status_code == 200


# ── Main ────────────────────────────────────────────────────────────────────

async def main():
    print("\nMINER cURL / REQUEST-RESPONSE TEST")
    print("Miner URL:", MINER_URL)
    print()

    # Test 1: availability (simple GET, no auth)
    alive = test_availability()
    if not alive:
        print("\nMiner is not reachable. Make sure it is running:")
        print("  uvicorn miner.main:app --host 0.0.0.0 --port 8001")
        return

    # Test 2: full challenge (signed POST)
    await test_challenge()


if __name__ == "__main__":
    asyncio.run(main())
